version: "3"
services:
  kafka:
    build: 
        context: ./kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    volumes:
      - kafka-logs:/tmp/kafka-logs
      - /var/run/docker.sock:/var/run/docker.sock
    # network_mode: bridge

volumes:
  kafka-logs: