version: "3"
services:
  kafka:
    build: 
        context: ./kafka
    ports:
      - "2181:2181"
      - "9092:9092"
  producer:
    build: 
      context: ./producer
    depends_on:
      - kafka
    links: 
      - kafka
  consumer:
    build: 
      context: ./consumer
    volumes:
        - ${PWD}/volume/db.txt:/opt/app/db.txt
    depends_on:
      - kafka
    links: 
      - kafka