version: "3"
services:
  kafka:
    build: 
        context: ./kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # network_mode: bridge
  producer:
    build: 
      context: ./producer
    depends_on:
      - kafka
    links: 
      - kafka

#volumes: